 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA', '--build-arg', 'SNOWPACK_PUBLIC_GOOGLE_API_KEY=${_SNOWPACK_PUBLIC_GOOGLE_API_KEY}', '--build-arg', 'BASIC_AUTH_PW=${_BASIC_AUTH_PW}', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA']
 images:
 - 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA'
