 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA', '--build-arg', 'SNOWPACK_PUBLIC_GOOGLE_API_KEY=${_SNOWPACK_PUBLIC_GOOGLE_API_KEY}', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'meetmethere-app'
   - '--image'
   - 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA'
   - '--region'
   - 'europe-north1'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/$PROJECT_ID/meetmethere-app:$COMMIT_SHA'
