# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Google.

# Controls when the action will run. 
on:
  # Triggers the workflow on push event but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env: 
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  SERVICE_NAME: meetmethere-app
  REGION: europe-central2-a

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Sets up google cloud SDK
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_acount_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
      
      # Builds the project in cloud
      - name: Build
        run: |-
          gcloud build submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      
      # Deploys to cloud run
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed"
            --quiet
          
      
